# see https://docs.docker.com/compose/compose-file/compose-file-v3/#args

version: "3.4"

x-keycloak_environment: &keycloak_environment
  DB_VENDOR: POSTGRES
  DB_DATABASE: keycloak
  DB_USER: keycloak
  DB_SCHEMA: public
  DB_PASSWORD: password
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: Pa55w0rd
  # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
  #JDBC_PARAMS: "ssl=true"

x-postgres_environment: &postgres_environment
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: password

services:
  postgres_dev:
    image: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      <<: *postgres_environment
  keycloak_dev:
    image: quay.io/keycloak/keycloak:latest
    environment:
      <<: *keycloak_environment
      DB_ADDR: postgres_dev
    ports:
      - 8080:8080
    depends_on:
      - postgres_dev

  postgres_test:
    image: postgres
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    environment:
      <<: *postgres_environment
  keycloak_test:
    image: quay.io/keycloak/keycloak:latest
    environment:
      <<: *keycloak_environment
      DB_ADDR: postgres_test
    command:
      - "-b 0.0.0.0"
      - "-Djboss.http.port=8081"
    ports:
      - 8081:8081
    depends_on:
      - postgres_test

  postgres_prod:
    image: postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      <<: *postgres_environment
  keycloak_prod:
    image: quay.io/keycloak/keycloak:latest
    environment:
      <<: *keycloak_environment
      DB_ADDR: postgres_prod
    command:
      - "-b 0.0.0.0"
      - "-Djboss.http.port=8082"
    ports:
      - 8082:8082
    depends_on:
      - postgres_prod

volumes:
  postgres_data_dev:
    driver: local
  postgres_data_test:
    driver: local
  postgres_data_prod:
    driver: local
